apis:
  - inference
  - safety

distribution_spec:
  provider_map:
    inference:
      - provider_id: meta-reference
        provider_type: inline::meta-reference
        config: {}
    safety:
      - provider_id: llama-guard
        provider_type: inline::llama-guard
        config: {}

models:
  - model_id: Llama-4-Scout-17B-16E-Instruct
    provider_id: meta-reference
  - model_id: Llama-4-Maverick-17B-128E-Instruct
    provider_id: meta-reference

providers:
  inference:
    - provider_id: meta-reference
      provider_type: inline::meta-reference
      config: {}

  safety:
    - provider_id: llama-guard
      provider_type: inline::llama-guard
      config: {}

image_name: llama-scout-stack

server:
  host: localhost
  port: 8321 